use_frameworks!

platform :ios, '10.0'

target 'youngminSDK_Example' do
  pod 'youngminSDK', :path => '../'

  target 'youngminSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
